# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
comments_first = Comment.create([{email: 'harshit@cmu.edu', body: 'Nice work'}, {email: 'hello@yahoo.com', body: 'Great post'}])
comments_second = Comment.create([{email: 'awesome@ness.com', body: 'Awesome'}])
Post.create(title: 'F-16', text: 'The General Dynamics F-16 Fighting Falcon is a single-engine multirole fighter aircraft originally developed by General Dynamics for the United States Air Force.', comments: comments_first)
Post.create(title: 'Sukhoi Su-30', text: 'The Sukhoi PAK FA (Russian: Сухой ПАК ФА, Russian: Перспективный авиационный комплекс фронтовой авиации, Perspektivny Aviatsionny Kompleks Frontovoy Aviatsii, literally "Prospective Airborne Complex of Frontline Aviation") is a twin-engine jet fighter being developed by Sukhoi for the Russian Air Force. The Sukhoi T-50 is the prototype for PAK FA. The PAK FA is one of only a handful of stealth jet programs worldwide. The PAK FA, a fifth generation jet fighter, is intended to be the successor to the MiG-29 and Su-27 in the Russian inventory and serve as the basis of the Sukhoi/HAL FGFA being developed with India. The T-50 prototype performed its first flight 29 January 2010. The Russian Defence Ministry will purchase the first 10 evaluation example aircraft after 2012 and then 60 production standard aircraft after 2016. The first batch of fighters will be delivered with current technology engines. The PAK-FA is expected to have a service life of about 30–35 years. The T-50\' s maiden flight had been repeatedly postponed since early 2007 as the aircraft encountered unspecified technical problems.Alexander Zelin admitted as recently as August 2009 that problems with the engine and in technical research remained unsolved.On 28 February 2009, Mikhail Pogosyan announced that the airframe for the aircraft was almost finished and that the first prototype should be ready by August 2009.On 20 August 2009, Pogosyan said that the first flight would be by year\'s end. Konstantin Makiyenko, deputy head of the Moscow-based Centre for Analysis of Strategies and Technologies said that "even with delays", the aircraft would likely make its first flight by January or February, adding that it would take five to ten years for commercial production.', comments: comments_second)